export const Gallery_info = [
    {
        img:'..//Gallery/1.jpg'
    },
    {
        img:'../Gallery/2.jpg'
    },
    {
        img:'../Gallery/3.jpg'
    },
    {
        img:'../Gallery/4.jpg'
    },
    {
        img:'../Gallery/5.jpg'
    },
    {
        img:'../Gallery/6.jpg'
    },
    {
        img:'../Gallery/7.jpg'
    },
    {
        img:'../Gallery/8.jpg'
    },
    {
        img:'../Gallery/9.jpg'
    },
    {
        img:'../Gallery/10.jpg'
    },
    {
        img:'../Gallery/11.jpg'
    },
    {
        img:'../Gallery/12.jpg'
    },
    {
        img:'../Gallery/13.jpg'
    },
    {
        img:'../Gallery/14.jpg'
    },
    {
        img:'../Gallery/15.jpg'
    },
    {
        img:'../Gallery/16.jpg'
    },
    {
        img:'../Gallery/17.jpg'
    },
    {
        img:'../Gallery/18.jpg'
    },
    {
        img:'../Gallery/19.jpg'
    },
    {
        img:'../Gallery/20.jpg'
    },
    {
        img:'../Gallery/21.jpg'
    },
    {
        img:'../Gallery/22.jpg'
    },
    {
        img:'../Gallery/23.jpg'
    },
    {
        img:'../Gallery/24.jpg'
    },
    {
        img:'../Gallery/25.jpg'
    },
    {
        img:'../Gallery/26.jpg'
    },
    {
        img:'../Gallery/27.jpg'
    },
    {
        img:'../Gallery/28.jpg'
    },
    {
        img:'../Gallery/29.jpg'
    },
    {
        img:'../Gallery/30.jpg'
    },
]


export const ChargeX_info = [
    {
        img:'../Gallery/31.jpg'
    },
    {
        img:'../Gallery/32.jpg'
    },
    {
        img:'../Gallery/33.jpg'
    },
    {
        img:'../Gallery/34.jpg'
    },
    {
        img:'../Gallery/35.jpg'
    },
    {
        img:'../Gallery/36.jpg'
    },
    {
        img:'../Gallery/37.jpg'
    },
    {
        img:'../Gallery/38.jpg'
    },
    {
        img:'../Gallery/39.jpg'
    },
    {
        img:'../Gallery/40.jpg'
    },
    {
        img:'../Gallery/41.jpg'
    },
    {
        img:'../Gallery/42.jpg'
    },
    {
        img:'../Gallery/95.jpg'
    },
    {
        img:'../Gallery/96.jpg'
    },
    {
        img:'../Gallery/97.jpg'
    },
    {
        img:'../Gallery/98.jpg'
    },
    {
        img:'../Gallery/99.jpg'
    },
    {
        img:'../Gallery/100.jpg'
    },
    {
        img:'../Gallery/101.jpg'
    },
    {
        img:'../Gallery/102.jpg'
    },
    {
        img:'../Gallery/103.jpg'
    },
    {
        img:'../Gallery/104.jpg'
    },
    {
        img:'../Gallery/105.jpg'
    },
    {
        img:'../Gallery/106.jpg'
    },
    {
        img:'../Gallery/107.jpg'
    },
    {
        img:'../Gallery/108.jpg'
    },
    {
        img:'../Gallery/109.jpg'
    },
    {
        img:'../Gallery/110.jpg'
    },
    {
        img:'../Gallery/117.jpg'
    },
    {
        img:'../Gallery/112.jpg'
    },
    {
        img:'../Gallery/113.jpg'
    },
    {
        img:'../Gallery/114.jpg'
    },
    {
        img:'../Gallery/115.jpg'
    },
    {
        img:'../Gallery/116.jpg'
    },
    {
        img:'../Gallery/111.jpg'
    },

    {
        img:'../Gallery/119.jpg'
    },
    {
        img:'../Gallery/120.jpg'
    },
    {
        img:'../Gallery/121.jpg'
    },
    {
        img:'../Gallery/122.jpg'
    },
    {
        img:'../Gallery/123.jpg'
    },
    {
        img:'../Gallery/124.jpg'
    },
    {
        img:'../Gallery/125.jpg'
    },
    {
        img:'../Gallery/134.jpg'
    },
    {
        img:'../Gallery/135.jpg'
    },
    {
        img:'../Gallery/126.jpg'
    },
    {
        img:'../Gallery/127.jpg'
    },
    {
        img:'../Gallery/128.jpg'
    },
    {
        img:'../Gallery/129.jpg'
    },
    {
        img:'../Gallery/130.jpg'
    },
    {
        img:'../Gallery/131.jpg'
    },
    {
        img:'../Gallery/132.jpg'
    },
    {
        img:'../Gallery/133.jpg'
    },
    {
        img:'../Gallery/136.jpg'
    },
    
]


export const Pantheon_info = [ 
    {
        img:'../Gallery/90.jpg'
    },
    {
        img:'../Gallery/91.jpg'
    },
    {
        img:'../Gallery/92.jpg'
    },
    {
        img :'../Gallery/75.jpg '
    },
    {
        img :'../Gallery/76.jpg '
    },
    {
        img :'../Gallery/77.jpg '
    },
    {
        img :'../Gallery/78.jpg '
    },
    {
        img :'../Gallery/79.jpg '
    },
    {
        img :'../Gallery/80.jpg '
    },
    {
        img :'../Gallery/81.jpg '
    },
    {
        img :'../Gallery/82.jpg '
    },
    {
        img :'../Gallery/83.jpg '
    },
    {
        img :'../Gallery/84.jpg '
    },
    {
        img :'../Gallery/85.jpg '
    },
    {
        img :'../Gallery/86.jpg '
    },
    {
        img :'../Gallery/87.jpg '
    },
    {
        img :'../Gallery/88.jpg '
    },
    {
        img :'../Gallery/89.jpg '
    },
]