export const Gallery_info = [

    {
        img:'..//Gallery/1.jpg'
    },
    {
        img:'../Gallery/2.jpg'
    },
    {
        img:'../Gallery/3.jpg'
    },
    {
        img:'../Gallery/4.jpg'
    },
    {
        img:'../Gallery/5.jpg'
    },
    {
        img:'../Gallery/6.jpg'
    },
    {
        img:'../Gallery/7.jpg'
    },
    {
        img:'../Gallery/8.jpg'
    },
    {
        img:'../Gallery/9.jpg'
    },
    {
        img:'../Gallery/10.jpg'
    },
    {
        img:'../Gallery/11.jpg'
    },
    {
        img:'../Gallery/12.jpg'
    },
    {
        img:'../Gallery/13.jpg'
    },
    {
        img:'../Gallery/14.jpg'
    },
    {
        img:'../Gallery/15.jpg'
    },
    {
        img:'../Gallery/16.jpg'
    },
    {
        img:'../Gallery/17.jpg'
    },
    {
        img:'../Gallery/18.jpg'
    },
    {
        img:'../Gallery/19.jpg'
    },
    {
        img:'../Gallery/20.jpg'
    },
    {
        img:'../Gallery/21.jpg'
    },
    {
        img:'../Gallery/22.jpg'
    },
    {
        img:'../Gallery/23.jpg'
    },
]